### PR TITLE
Upload Splatoon 2 [0100F8F0000A2000] vertical cover

### PR DESCRIPTION
**Pull request by linuxct**
Non-stretched version: [splatoon2-2](https://user-images.githubusercontent.com/3966313/167275457-ea6eb6bd-2b62-4ee4-bd03-932fa2fe886b.jpg)

### CODE REVIEW

**Comment by sodasoba1** [comment]
Icons in this repo need to be 256x256 pixels and under 120kb in size non progressive jpg otherwise it won't work.
Resize the icon without keeping the ratio and it should work fine when applied.

Otherwise consider uploading it in 600*900 to steamgriddb

**Comment by linuxct** [comment]
> Icons in this repo need to be 256x256 pixels and under 120kb in size non progressive jpg otherwise it won't work. Resize the icon without keeping the ratio and it should work fine when applied.
> 
> Otherwise consider uploading it in 600*900 to steamgriddb

Oh right, I'm aware. The image I committed is 256x256 rescaled from a 2:3 image, non progressive jpg and is less than 90k. The image in the commit description is just for the sake of showing how it will look like on the Switch once applied.  

I'm already using it and it works fine, see below:  
IMG_20220509_004619_800

On a separate note, many thanks for SwitchDeck! Any chances you will publish the unpacked patches for the theme? I would like to slightly adjust the position for the first game in the home screen grid as it looks way too far on the right for me. Otherwise the theme is perfect, thank you.

**Comment by sodasoba1** [comment]
I have already published them:
https://github.com/sodasoba1/nx-vertical-themes/tree/master/SwitchDeck-14.0.0

Be aware if you move the icons too far to the left you may break scrolling, and how the cursor works

I'll merge the commit later when I push more icons  myself I usually try to push 10+ at once smaller commits are usually to help people.
So if you make more icons please add them

**Comment by linuxct** [comment]
> I'll merge the commit later when I push more icons myself I usually try to push 10+ at once smaller commits are usually to help people. So if you make more icons please add them

Ah sure, I will go through my library and see if there are any missing cover that I can do. Will push if so 👍

**Comment by sodasoba1** [comment]
> 

That would be amazing I've literally done this solo and after 4500+ icons some extra help would be awesome!

I've moved to 2:3 ratio for vertical icons as of late.
I usually upload to steamgriddb (600*900) then add a resized version to my repo/hdd I was planning on revisiting some older icons but I might have to separate older icons with the different aspect ratio I'm uncertain of I need to.

I also add games not yet released as an attempt to keep the vertical themes relevant and ahead of anyone requesting icons.

**Pull request merged**
